/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-OFDM_OOT
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_OFDM_OOT_API_H
#define INCLUDED_OFDM_OOT_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_OFDM_OOT_EXPORTS
#define OFDM_OOT_API __GR_ATTR_EXPORT
#else
#define OFDM_OOT_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_OFDM_OOT_API_H */
