/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(autocorr_cpp_cccc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(64647f354d8bae64a56f8b416e986021)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/OFDM_OOT/autocorr_cpp_cccc.h>
// pydoc.h is automatically generated in the build directory
#include <autocorr_cpp_cccc_pydoc.h>

void bind_autocorr_cpp_cccc(py::module& m)
{

    using autocorr_cpp_cccc    = gr::OFDM_OOT::autocorr_cpp_cccc;


    py::class_<autocorr_cpp_cccc, gr::block, gr::basic_block,
        std::shared_ptr<autocorr_cpp_cccc>>(m, "autocorr_cpp_cccc", D(autocorr_cpp_cccc))

        .def(py::init(&autocorr_cpp_cccc::make),
           D(autocorr_cpp_cccc,make)
        )
        



        ;




}








