/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(autocorr_cpp_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0d9bbfe42267d63c12620a20688a55ca)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/OFDM_OOT/autocorr_cpp_cc.h>
// pydoc.h is automatically generated in the build directory
#include <autocorr_cpp_cc_pydoc.h>

void bind_autocorr_cpp_cc(py::module& m)
{

    using autocorr_cpp_cc    = gr::OFDM_OOT::autocorr_cpp_cc;


    py::class_<autocorr_cpp_cc, gr::block, gr::basic_block,
        std::shared_ptr<autocorr_cpp_cc>>(m, "autocorr_cpp_cc", D(autocorr_cpp_cc))

        .def(py::init(&autocorr_cpp_cc::make),
           D(autocorr_cpp_cc,make)
        )
        



        ;




}








