/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cfar_detector_cpp_ccc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2e071f8a490cf2065f6e6a602ccdf743)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/OFDM_OOT/cfar_detector_cpp_ccc.h>
// pydoc.h is automatically generated in the build directory
#include <cfar_detector_cpp_ccc_pydoc.h>

void bind_cfar_detector_cpp_ccc(py::module& m)
{

    using cfar_detector_cpp_ccc    = gr::OFDM_OOT::cfar_detector_cpp_ccc;


    py::class_<cfar_detector_cpp_ccc, gr::block, gr::basic_block,
        std::shared_ptr<cfar_detector_cpp_ccc>>(m, "cfar_detector_cpp_ccc", D(cfar_detector_cpp_ccc))

        .def(py::init(&cfar_detector_cpp_ccc::make),
           D(cfar_detector_cpp_ccc,make)
        )
        



        ;




}








